import React, { useMemo, useState, useEffect } from 'react';
import { ArrowRight, CalendarDays, Check, Clock3, MapPin, MessageCircle, Plus, Users, X } from 'lucide-react';
import { departments } from './Auth.jsx';
import { CommunityPost } from './CommunityPost.jsx';

const groups = ['General', ...departments];
const weekDays=['MON 21','TUE 22','WED 23','THU 24','FRI 25'];
export const defaultFacilityHours=[{id:'s1',day:0,time:'9 AM',title:'SEM orientation',space:'Materials Science · Lab 204',resourceId:'sem',state:'ongoing'},{id:'s2',day:0,time:'1 PM',title:'Dance rehearsal',space:'Arts · Studio 2',resourceId:'dance',state:'reserved'},{id:'s3',day:1,time:'10 AM',title:'Study group',space:'Main Library · Room 3B',resourceId:'study',state:'available'},{id:'s4',day:2,time:'11 AM',title:'Cell imaging',space:'Life Sciences · Core Facility',resourceId:'confocal',state:'ongoing'},{id:'s5',day:2,time:'3 PM',title:'Music practice',space:'Student Center · Music Wing',resourceId:'music',state:'reserved'},{id:'s6',day:3,time:'2 PM',title:'Open maker lab',space:'Engineering · Maker Space',resourceId:'printer',state:'available'},{id:'s7',day:4,time:'12 PM',title:'Quiet study block',space:'Main Library · Room 3B',resourceId:'study',state:'reserved'}];
const scheduleResources=[['sem','Scanning Electron Microscope','Materials Science · Lab 204'],['laser','Laser Cutter','Design & Innovation · Workshop'],['spectro','Spectrophotometer','Chemistry · Lab 118'],['printer','3D Printer Farm','CSE · Maker Space'],['confocal','Confocal Microscope','Bio Tech · Core Facility'],['utm','Universal Testing Machine','Civil · Lab 06'],['music','Music Practice Hall','Student Center · Music Wing'],['dance','Dance Studio','Arts Building · Studio 2'],['study','Quiet Study Room','Main Library · Room 3B'],['bioanalyzer','Biomolecular Analyzer','Bio Tech · Lab 112'],['hydraulic','Hydraulic Test Bench','Civil · Lab 09'],['robotics','Robotics Workbench','Robotics · Lab 3'],['digital','Digital Systems Lab','CSE · Block A, Lab 201'],['maclab','Mac Lab','Visual Communication · Media Wing'],['viscom','Visual Communication Studio','Visual Communication · Studio 2'],['aerospace','Aerospace Systems Lab','Aero Space · Flight Systems Block'],['foodtech','Food Technology Pilot Plant','Food Technology · Process Lab'],['agri','Agriculture Field Lab','Agri · Greenhouse'],['physio','Physiotherapy Skills Lab','Physio · Health Sciences'],['law','Moot Court Hall','Law · Academic Block C'],['architecture','Architecture Design Studio','Architectural · Design Block'],['mechatronics','Mechatronics Prototyping Lab','Mechatronics · Engineering Block']];
export const seedPosts = [
  {id:'seed-project',type:'Project help',group:'General',title:'Looking for a biology teammate for a climate hackathon',body:'We’re building a low-cost water quality dashboard this weekend. Hoping to meet someone who knows field sampling or environmental chemistry. Students from every department welcome.',author:'Jordan Rivera',department:'Mechanical Engineering',time:'2 hours ago',crossDepartment:true,createdAt:1},
  {id:'seed-achievement',type:'Achievement',group:'Engineering',title:'Our first working prototype is here! 🎉',body:'After three weeks in the maker space, our water quality sensor is finally reading accurately. Huge thanks to the EE folks who helped us debug the signal processing.',author:'Jordan Rivera',department:'Mechanical Engineering',time:'4 hours ago',createdAt:2},
  {id:'seed-meetup',type:'Activity / meetup',group:'General',title:'Anyone up for basketball this evening?',body:'I have a ball and the outdoor court is free. Come shoot around, no experience needed.',author:'Maya Lin',department:'Life Sciences',time:'Today',place:'North Court',when:'Today · 6:00 PM',capacity:10,attendees:['Maya Lin','Alex Morgan'],createdAt:3},
  {id:'seed-project-2',type:'Project help',group:'Materials Science',title:'Need a designer for our sustainable packaging hackathon team',body:'We have two materials researchers and would love a design student to help with rapid prototyping this Saturday. Open to any department.',author:'Priya Shah',department:'Materials Science',time:'Yesterday',crossDepartment:true,createdAt:4},
  {id:'seed-achievement-2',type:'Achievement',group:'Life Sciences',title:'Poster accepted at the undergraduate research symposium',body:'Our cell imaging project was accepted for this year’s symposium. Thanks to everyone who gave feedback on our first draft!',author:'Maya Lin',department:'Life Sciences',time:'Yesterday',createdAt:5},
  {id:'seed-ese-help',type:'Project help',group:'ESE',title:'Looking for an ESE teammate for an embedded systems challenge',body:'We are prototyping a low-power sensor node and need another student to help with PCB design and testing. ESE students, message us if you want to join.',author:'Arun K.',department:'ESE',time:'1 hour ago',crossDepartment:true,createdAt:6},
  {id:'seed-cse-team',type:'Competition / team',group:'CSE',title:'Building a team for the inter-college app sprint',body:'Looking for a frontend developer and someone interested in accessibility testing. We are meeting in the Digital Systems Lab this Friday.',author:'Nisha R.',department:'CSE',time:'3 hours ago',crossDepartment:true,createdAt:7},
  {id:'seed-ece-project',type:'Project help',group:'ECE',title:'Need help testing our smart irrigation prototype',body:'Our ECE team has the controller working and would love an agriculture student to help validate it with real soil moisture readings.',author:'Dev M.',department:'ECE',time:'Today',taggedDepartment:'Agri',crossDepartment:true,createdAt:8},
  {id:'seed-general-achievement',type:'Achievement',group:'General',title:'Robotics club places in the campus build challenge',body:'Our mixed-department team earned second place with a small line-following robot. Thank you to everyone who shared parts and debugging tips.',author:'Leah T.',department:'Robotics',time:'Yesterday',createdAt:9}
];
function saved(key, fallback){try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}}
function accountKey(key,userId){return `${key}:${encodeURIComponent(String(userId||'guest').trim().toUpperCase())}`}
function loadPosts(){const current=saved('commonground-posts',null);if(!Array.isArray(current))return seedPosts;const ids=new Set(current.map(post=>post.id));return [...current,...seedPosts.filter(post=>!ids.has(post.id))]}

export function Communities({notify,onOfferHelp,author='Student',userId='guest',userDepartment='General'}) {
  const [posts,setPosts]=useState(loadPosts);
  const [rsvps,setRsvps]=useState(()=>saved(accountKey('commonground-meetup-rsvps',userId),{}));
  const [offers,setOffers]=useState(()=>saved(accountKey('commonground-collaboration-offers',userId),{}));
  const [appreciations,setAppreciations]=useState(()=>saved(accountKey('commonground-appreciations',userId),{}));
  const [replies,setReplies]=useState(()=>saved(accountKey('commonground-post-replies',userId),{}));
  const [group,setGroup]=useState(userDepartment||'General');
  const communityGroups=useMemo(()=>[...new Set(['General',...departments,userDepartment].filter(Boolean))],[userDepartment]);
  const [type,setType]=useState('Project help');
  const [taggedDepartment,setTaggedDepartment]=useState('');
  const [title,setTitle]=useState('');
  const [body,setBody]=useState('');
  const [place,setPlace]=useState('');
  const [when,setWhen]=useState('');
  const [capacity,setCapacity]=useState('');
  const [showComposer,setShowComposer]=useState(false);
  useEffect(()=>{try{localStorage.setItem('commonground-posts',JSON.stringify(posts))}catch{}},[posts]);
  useEffect(()=>{try{localStorage.setItem(accountKey('commonground-meetup-rsvps',userId),JSON.stringify(rsvps))}catch{}},[rsvps,userId]);
  useEffect(()=>{try{localStorage.setItem(accountKey('commonground-collaboration-offers',userId),JSON.stringify(offers))}catch{}},[offers,userId]);
  useEffect(()=>{try{localStorage.setItem(accountKey('commonground-appreciations',userId),JSON.stringify(appreciations))}catch{}},[appreciations,userId]);
  useEffect(()=>{try{localStorage.setItem(accountKey('commonground-post-replies',userId),JSON.stringify(replies))}catch{}},[replies,userId]);
  useEffect(()=>{const openSharedPost=()=>{const id=decodeURIComponent(window.location.hash.slice(6));if(!window.location.hash.startsWith('#post-')||!id)return;const post=posts.find(p=>p.id===id);if(!post)return;setGroup(post.taggedDepartment||post.group||'General');window.setTimeout(()=>document.getElementById(`post-${id}`)?.scrollIntoView({behavior:'smooth',block:'center'}),180)};openSharedPost();window.addEventListener('hashchange',openSharedPost);return()=>window.removeEventListener('hashchange',openSharedPost)},[posts]);
  const visible=useMemo(()=>posts.filter(p=>group==='General'?p.group==='General'||p.crossDepartment||p.type==='Activity / meetup':p.group===group||p.crossDepartment||p.taggedDepartment===group||p.type==='Activity / meetup').sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)),[posts,group]);
  const publish=()=>{if(!title.trim()||!body.trim())return;const postGroup=type==='Activity / meetup'?'General':group;const item={id:globalThis.crypto?.randomUUID?.()||`${Date.now()}`,type,group:postGroup,title:title.trim(),body:body.trim(),author,department:userDepartment,time:'Just now',createdAt:Date.now(),crossDepartment:type==='Project help'||type==='Competition / team',taggedDepartment:type==='Activity / meetup'?'':taggedDepartment,...(type==='Activity / meetup'?{place:place.trim(),when,capacity:capacity?Number(capacity):null,attendees:[]}: {})};setPosts(v=>[item,...v]);if(type==='Activity / meetup')setRsvps(v=>({...v,[item.id]:true}));setTitle('');setBody('');setPlace('');setWhen('');setCapacity('');setTaggedDepartment('');setShowComposer(false);notify(taggedDepartment?`Post tagged for ${taggedDepartment}`:type==='Activity / meetup'?'Post shared with the whole college':'Post shared with students across departments')};
  const toggleRsvp=(post)=>setRsvps(v=>({...v,[post.id]:!v[post.id]}));
  const toggleHelp=(post)=>{const active=!offers[post.id];setOffers(v=>({...v,[post.id]:active}));onOfferHelp?.(post,active);notify(active?'Help offer added to My bookings':'Help offer removed from My bookings')};
  const toggleAppreciation=(post)=>{const active=!appreciations[post.id];setAppreciations(v=>({...v,[post.id]:active}));notify(active?'Appreciation added':'Appreciation removed')};
  const addReply=(post,text)=>setReplies(v=>({...v,[post.id]:[...(v[post.id]||[]),{id:globalThis.crypto?.randomUUID?.()||`${Date.now()}`,author,text,createdAt:'Just now'}]}));
  const sharePost=async(post)=>{const url=`${window.location.origin}/#post-${post.id}`;try{if(navigator.share){await navigator.share({title:post.title,text:post.body,url});return}await navigator.clipboard.writeText(url);notify('Post link copied')}catch(error){if(error?.name==='AbortError')return;try{const field=document.createElement('textarea');field.value=url;document.body.appendChild(field);field.select();document.execCommand('copy');field.remove();notify('Post link copied')}catch{notify('Could not share this post')}}};
  return <div className="page-content inner-page"><div className="eyebrow"><span className="eyebrow-line"/> CAMPUS, TOGETHER</div><h1>Good work is <span>shared.</span></h1><p className="hero-sub">Find collaborators, celebrate student work, or make plans together.</p>
    <div className="community-layout"><section className="feed">
      <div className="community-tools"><div><b>{group==='General'?'College-wide community':`${group} community`}</b><span>{group==='General'?'Achievements, meetups, and cross-department requests':'Department posts plus requests tagged for this department'}</span></div><button className="primary-btn" onClick={()=>setShowComposer(v=>!v)}>{showComposer?<X size={14}/>:<Plus size={14}/>} {showComposer?'Close':'Create a post'}</button></div>
      {showComposer&&<div className="composer community-composer"><label className="form-label">POST TYPE</label><select className="form-input" value={type} onChange={e=>setType(e.target.value)}><option>Project help</option><option>Competition / team</option><option>Achievement</option><option>Activity / meetup</option></select>{type!=='Activity / meetup'?<><label className="form-label">POST TO COMMUNITY</label><select className="form-input" value={group} onChange={e=>setGroup(e.target.value)}>{communityGroups.map(g=><option key={g}>{g}</option>)}</select><label className="form-label">TAG A DEPARTMENT (OPTIONAL)</label><select className="form-input" value={taggedDepartment} onChange={e=>setTaggedDepartment(e.target.value)}><option value="">No department tag</option>{communityGroups.filter(d=>d!==group).map(d=><option key={d}>{d}</option>)}</select><div className="need-note"><Users size={14}/>The tagged department will see this request in its community feed.</div></>:<div className="need-note"><Users size={14}/>Activity invitations are shared college-wide in the General community.</div>}<label className="form-label">TITLE</label><input className="form-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder={type==='Activity / meetup'?'Anyone up for basketball?':type==='Achievement'?'Share what you accomplished':type==='Competition / team'?'Looking for teammates for a competition':'What help or teammate are you looking for?'}/><label className="form-label">DETAILS</label><textarea className="form-input community-body" value={body} onChange={e=>setBody(e.target.value)} placeholder="Add helpful details for other students..."/>{type==='Activity / meetup'&&<div className="meetup-fields"><div><label className="form-label">WHEN</label><input className="form-input" type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></div><div><label className="form-label">WHERE</label><input className="form-input" value={place} onChange={e=>setPlace(e.target.value)} placeholder="Court, studio, library..."/></div><div><label className="form-label">MAX PEOPLE (OPTIONAL)</label><input className="form-input" type="number" min="2" value={capacity} onChange={e=>setCapacity(e.target.value)} placeholder="No limit"/></div></div>}<div className="composer-actions"><span>{type==='Project help'||type==='Competition / team'?'Open to students across departments.':type==='Activity / meetup'?'Visible college-wide.':`Posting to ${group}.`}</span><button className="primary-btn" disabled={!title.trim()||!body.trim()||(type==='Activity / meetup'&&(!place.trim()||!when))} onClick={publish}>Publish post <ArrowRight size={14}/></button></div></div>}
      {visible.map(p=><CommunityPost key={p.id} post={p} author={author} joined={!!rsvps[p.id]} helpOffered={!!offers[p.id]} appreciated={!!appreciations[p.id]} replies={replies[p.id]||[]} onRsvp={post=>toggleRsvp(post)} onHelp={post=>toggleHelp(post)} onAppreciate={post=>toggleAppreciation(post)} onReply={addReply} onShare={sharePost} notify={notify}/>)}      {!visible.length&&<div className="inner-panel community-empty"><MessageCircle size={22}/><b>No posts in this group yet</b><span>Start the conversation or check the college-wide feed.</span></div>}
    </section><aside className="community-rail"><div className="community-select-card"><label htmlFor="community-select">DEPARTMENT COMMUNITY</label><select id="community-select" className="form-input" value={group} onChange={e=>setGroup(e.target.value)}>{communityGroups.map(g=><option key={g} value={g}>{g==='General'?'General · All campus':g}</option>)}</select></div><div className="rail-card rail-feature"><div className="section-kicker">CAMPUS, TOGETHER</div><h3>Practice is better<br/>with people.</h3><p>Book music, dance, and study spaces, or post an invite to find company.</p><div className="rail-date">MUSIC · DANCE · STUDY</div><button onClick={()=>notify('Choose Spaces in the resource library to browse practice halls.')}>Browse practice spaces <ArrowRight size={14}/></button></div><div className="rail-help"><Users size={17}/><b>{groups.length} campus communities</b><span>Choose a department from the list. Project help reaches students across campus.</span></div></aside></div>
  </div>;
}

export function BookingPage({booked,onDiscover,onCancel}){return <div className="page-content inner-page"><div className="eyebrow"><span className="eyebrow-line"/> YOUR WORKSPACE</div><h1>Time well <span>spent.</span></h1><p className="hero-sub">Your confirmed facility bookings and collaboration offers.</p><div className="inner-panel"><div className="panel-heading"><div><div className="section-kicker">YOUR ACTIVITY</div><h2>My bookings<span className="title-period">.</span></h2></div><button className="primary-btn" onClick={onDiscover}><Plus size={15}/> Find a resource</button></div>{booked.length?<div className="booking-list">{booked.map(b=><div className={`booking-row ${b.kind==='help'?'collaboration-booking':''}`} key={b.id}><div className="booking-icon">{b.kind==='help'?<Users size={18}/>:<CalendarDays size={18}/>}</div><div className="booking-main"><b>{b.kind==='help'?`Help offer · ${b.name}`:b.name}</b><span>{b.kind==='help'?`${b.time} · Added ${b.date}`:`${b.date} · ${b.time}`}</span></div><span className="booking-status">{b.kind==='help'?'Help offered':'Booked'}</span><button className="small-quiet" onClick={()=>onCancel(b.id)}>{b.kind==='help'?'Withdraw':'Cancel'}</button></div>)}</div>:<div className="empty-state"><div className="empty-icon"><CalendarDays size={22}/></div><b>Nothing on the calendar yet</b><span>Choose a green hour or offer to help on a community post.</span><button className="text-link" onClick={onDiscover}>Explore resources <ArrowRight size={14}/></button></div>}</div></div>}

export function AdminBoard({booked,onUpdate}){const pending=booked.filter(b=>b.status==='Pending approval');return <div className="page-content inner-page"><div className="eyebrow"><span className="eyebrow-line"/> MANAGEMENT · DEMO VIEW</div><h1>Keep campus <span>moving.</span></h1><p className="hero-sub">Review student requests and keep a weekly view of shared facilities.</p><div className="admin-stats"><div><span>ACTIVE RESOURCES</span><b>48 <small>/ 56</small></b><em>Includes practice & study spaces</em></div><div><span>STUDENT REQUESTS</span><b>{booked.length}</b><em>Saved in this browser</em></div><div><span>PENDING APPROVALS</span><b>{pending.length}</b><em>Requires coordinator action</em></div><div><span>ACTIVE COMMUNITIES</span><b>{groups.length}</b><em>General + departments</em></div></div><section className="inner-panel admin-week-panel"><div className="panel-heading"><div><div className="section-kicker">SHARED FACILITIES</div><h2>Weekly schedule<span className="title-period">.</span></h2></div><span className="schedule-sample-note">SAMPLE · SEP 22–26</span></div><div className="admin-week">{weekDays.map((d,i)=><div className="admin-day" key={d}><b>{d}</b>{facilityHours.filter(x=>x.day===i).map((x,j)=><div className={`admin-slot ${x.kind}`} key={`${d}-${j}`}><strong>{x.time}</strong><span>{x.title}</span><small>{x.space}</small></div>)}</div>)}</div></section><div className="inner-panel approvals-panel admin-requests"><div className="section-kicker">COORDINATOR INBOX</div><h2>Booking requests<span className="title-period">.</span></h2>{booked.length?booked.map((b,i)=><div className="approval-row" key={b.id}><div className={`avatar approval-avatar av-${i%3}`}>AM</div><div><b>Alex Morgan</b><span>{b.name}</span><small>{b.date} · {b.time}</small></div><span className={`booking-status status-${b.status.toLowerCase().replaceAll(' ','-')}`}>{b.status}</span>{b.status==='Pending approval'?<div className="approval-actions"><button title="Approve request" onClick={()=>onUpdate(b.id,'Approved')}><Check size={15}/></button><button title="Reject request" onClick={()=>onUpdate(b.id,'Declined')}><X size={15}/></button></div>:null}</div>):<div className="community-empty"><CalendarDays size={22}/><b>No booking requests yet</b><span>Student requests will appear here for review.</span></div>}</div></div>}

export function ManagementPortal({booked,onUpdate,schedule,onAddSlot,onRemoveSlot}){
 const[day,setDay]=useState(0),[time,setTime]=useState('9 AM'),[title,setTitle]=useState(''),[resourceId,setResourceId]=useState('sem'),[state,setState]=useState('reserved');
 const pending=booked.filter(b=>b.status==='Pending approval');
 const saveSlot=()=>{if(!title.trim())return;const resource=scheduleResources.find(x=>x[0]===resourceId);onAddSlot({id:globalThis.crypto?.randomUUID?.()||`${Date.now()}`,day:Number(day),time,title:title.trim(),space:resource[2],resourceId,state});setTitle('')};
 return <div className="page-content inner-page"><div className="eyebrow"><span className="eyebrow-line"/> MANAGEMENT · OPERATIONS PORTAL</div><h1>Keep campus <span>moving.</span></h1><p className="hero-sub">Review resource activity, coordinate facility schedules, and handle student requests.</p><div className="admin-stats"><div><span>ACTIVE RESOURCES</span><b>9</b><em>Labs, equipment & practice rooms</em></div><div><span>STUDENT BOOKINGS</span><b>{booked.length}</b><em>Saved in this browser</em></div><div><span>PENDING APPROVALS</span><b>{pending.length}</b><em>Requires coordinator action</em></div><div><span>COMMUNITY GROUPS</span><b>{groups.length}</b><em>General + departments</em></div></div>
  <section className="inner-panel admin-week-panel"><div className="panel-heading"><div><div className="section-kicker">RESOURCE OPERATIONS</div><h2>Weekly facility schedule<span className="title-period">.</span></h2></div><span className="schedule-sample-note">SAMPLE WEEK · SEP 21–25</span></div><div className="availability-legend"><span><i className="legend-dot red"/> Ongoing class / in use</span><span><i className="legend-dot yellow"/> Reserved</span><span><i className="legend-dot green"/> Available</span></div><div className="admin-week">{weekDays.map((d,i)=><div className="admin-day" key={d}><b>{d}</b>{schedule.filter(x=>x.day===i).map(x=><div className={`admin-slot ${x.state}`} key={x.id}><strong>{x.time}</strong><span>{x.title}</span><small>{x.space}</small><button title="Remove schedule entry" onClick={()=>onRemoveSlot(x.id)}><X size={11}/></button></div>)}</div>)}</div><div className="schedule-editor"><div><label className="form-label">DAY</label><select className="form-input" value={day} onChange={e=>setDay(e.target.value)}>{weekDays.map((d,i)=><option value={i} key={d}>{d}</option>)}</select></div><div><label className="form-label">TIME</label><select className="form-input" value={time} onChange={e=>setTime(e.target.value)}>{['9 AM','10 AM','11 AM','12 PM','1 PM','2 PM','3 PM','4 PM','5 PM','6 PM'].map(t=><option key={t}>{t}</option>)}</select></div><div><label className="form-label">RESOURCE / FACILITY</label><select className="form-input" value={resourceId} onChange={e=>setResourceId(e.target.value)}>{scheduleResources.map(r=><option key={r[0]} value={r[0]}>{r[1]}</option>)}</select></div><div><label className="form-label">ACTIVITY</label><input className="form-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Class, reservation, or open slot"/></div><div><label className="form-label">STATUS</label><select className="form-input" value={state} onChange={e=>setState(e.target.value)}><option value="ongoing">Ongoing class</option><option value="reserved">Reserved</option><option value="available">Available</option></select></div><button className="primary-btn" disabled={!title.trim()} onClick={saveSlot}><Plus size={14}/> Add schedule item</button></div></section>
  <div className="inner-panel approvals-panel admin-requests"><div className="section-kicker">COORDINATOR INBOX</div><h2>Booking requests<span className="title-period">.</span></h2>{booked.length?booked.map((b,i)=><div className="approval-row" key={b.id}><div className={`avatar approval-avatar av-${i%3}`}>ST</div><div><b>{b.student||'Student'}</b><span>{b.name}</span><small>{b.date} · {b.time}</small></div><span className={`booking-status status-${b.status.toLowerCase().replaceAll(' ','-')}`}>{b.status}</span>{b.status==='Pending approval'?<div className="approval-actions"><button title="Approve request" onClick={()=>onUpdate(b.id,'Approved')}><Check size={15}/></button><button title="Reject request" onClick={()=>onUpdate(b.id,'Declined')}><X size={15}/></button></div>:null}</div>):<div className="community-empty"><CalendarDays size={22}/><b>No booking requests yet</b><span>Student requests will appear here for review.</span></div>}</div>
 </div>
}


