import React, { useState } from 'react';
import { ArrowRight, Check, Clock3, Heart, MapPin, MessageCircle, Users } from 'lucide-react';

export function CommunityPost({post,author='Student',joined,helpOffered,appreciated,replies=[],onRsvp,onHelp,onAppreciate,onReply,onShare,notify}){
 const [replyOpen,setReplyOpen]=useState(false),[draft,setDraft]=useState('');
 const attendees=post.attendees||[];
 const count=attendees.length+(joined?1:0);
 const submitReply=()=>{if(!draft.trim())return;onReply(post,draft.trim());setDraft('');setReplyOpen(true)};
 return <article className="post-card enhanced-post" id={`post-${post.id}`}>
  <div className="post-head"><div className="avatar post-avatar">{post.author.split(' ').map(w=>w[0]).join('').slice(0,2)}</div><div className="post-author"><b>{post.author}</b><span>{post.department} · {post.group==='General'?'General community':post.group}</span></div><span className="post-time">{post.time}</span></div>
  <div className="post-content"><span className={`post-tag ${post.type==='Achievement'?'post-tag-0':post.type==='Activity / meetup'?'post-tag-1':'post-tag-2'}`}>{post.type}{post.crossDepartment?' · OPEN TO ALL DEPARTMENTS':''}</span>{post.taggedDepartment&&<span className="department-tag">FOR {post.taggedDepartment.toUpperCase()}</span>}<h3>{post.title}</h3><p>{post.body}</p>{post.type==='Activity / meetup'&&<div className="meetup-details"><div><Clock3 size={14}/>{post.when}</div><div><MapPin size={14}/>{post.place}</div><div><Users size={14}/>{count}{post.capacity?` / ${post.capacity}`:' going'}</div><button disabled={post.capacity&&count>=post.capacity&&!joined} className={`meetup-join ${joined?'joined':''}`} onClick={()=>onRsvp(post)}>{joined?<><Check size={13}/> Joined</>:<>Join <ArrowRight size={13}/></>}</button></div>}</div>
  <div className="post-actions">{post.crossDepartment&&<button className={helpOffered?'help-offered':''} onClick={()=>onHelp(post)}>{helpOffered?'✓':'＋'} <span>{helpOffered?'Help offered':'Offer to help'}</span></button>}<button className={`appreciate-button ${appreciated?'appreciated':''}`} aria-pressed={appreciated} onClick={()=>onAppreciate(post)}><Heart size={15} fill={appreciated?'currentColor':'none'}/><span>{appreciated?'Appreciated':'Appreciate'}</span></button><button className={replyOpen?'reply-active':''} aria-expanded={replyOpen} onClick={()=>setReplyOpen(v=>!v)}><MessageCircle size={14}/><span>Reply{replies.length?` · ${replies.length}`:''}</span></button><button onClick={()=>onShare(post)}><ArrowRight size={14}/><span>Share</span></button></div>
  {(replyOpen||replies.length>0)&&<div className="post-replies">{replies.map(reply=><div className="post-reply" key={reply.id}><div className="avatar reply-avatar">{reply.author.slice(0,2).toUpperCase()}</div><div><b>{reply.author}</b><p>{reply.text}</p><small>{reply.createdAt}</small></div></div>)}{replyOpen&&<div className="reply-composer"><textarea className="form-input" value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submitReply()}}} placeholder="Write a reply…" aria-label={`Reply to ${post.title}`}/><button className="primary-btn" disabled={!draft.trim()} onClick={submitReply}>Post reply <ArrowRight size={13}/></button></div>}</div>}
 </article>
}
