import React, { useEffect, useState } from 'react';
import { Activity, ArrowRight, BarChart3, CalendarDays, Clock3, Plus, Users, X } from 'lucide-react';

const weekDays=['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'];
const hours=['9 AM','10 AM','11 AM','12 PM','1 PM','2 PM','3 PM','4 PM','5 PM'];
const facilities=[['sem','Scanning Electron Microscope','Materials Science · Lab 204'],['laser','Laser Cutter','Design & Innovation · Workshop'],['spectro','Spectrophotometer','Chemistry · Lab 118'],['printer','3D Printer Farm','CSE · Maker Space'],['confocal','Confocal Microscope','Bio Tech · Core Facility'],['utm','Universal Testing Machine','Civil · Lab 06'],['music','Music Practice Hall','Student Center · Music Wing'],['dance','Dance Studio','Arts Building · Studio 2'],['study','Quiet Study Room','Main Library · Room 3B'],['bioanalyzer','Biomolecular Analyzer','Bio Tech · Lab 112'],['hydraulic','Hydraulic Test Bench','Civil · Lab 09'],['robotics','Robotics Workbench','Robotics · Lab 3'],['digital','Digital Systems Lab','CSE · Block A, Lab 201'],['maclab','Mac Lab','Visual Communication · Media Wing'],['viscom','Visual Communication Studio','Visual Communication · Studio 2'],['aerospace','Aerospace Systems Lab','Aero Space · Flight Systems Block'],['foodtech','Food Technology Pilot Plant','Food Technology · Process Lab'],['agri','Agriculture Field Lab','Agri · Greenhouse'],['physio','Physiotherapy Skills Lab','Physio · Health Sciences'],['law','Moot Court Hall','Law · Academic Block C'],['architecture','Architecture Design Studio','Architectural · Design Block'],['mechatronics','Mechatronics Prototyping Lab','Mechatronics · Engineering Block']];

export function ManagementPortal({booked=[],schedule=[],onAddSlot,onRemoveSlot}){
 const[day,setDay]=useState(0),[time,setTime]=useState('9 AM'),[title,setTitle]=useState(''),[resourceId,setResourceId]=useState('digital'),[state,setState]=useState('available'),[traffic,setTraffic]=useState({bookings:0,students:0,resourcesInUse:0,byResource:[]});
 useEffect(()=>{const load=()=>fetch('/api/traffic').then(r=>r.ok?r.json():null).then(v=>v&&setTraffic(v)).catch(()=>{});load();const t=setInterval(load,10000);return()=>clearInterval(t)},[booked.length]);
 const saveSlot=()=>{if(!title.trim())return;const resource=facilities.find(x=>x[0]===resourceId);onAddSlot({id:globalThis.crypto?.randomUUID?.()||`${Date.now()}`,day:Number(day),time,title:title.trim(),space:resource[2],resourceId,state});setTitle('')};
 const latestSchedule=new Map();schedule.forEach(x=>latestSchedule.set(`${x.day}|${x.resourceId}|${x.time}`,x));
 const effectiveSchedule=[...latestSchedule.values()];
 const hoursGrid=weekDays.map((label,i)=><div className="timetable-day" key={label}><b>{label}</b>{hours.map(hour=>{const items=effectiveSchedule.filter(x=>x.day===i&&x.time.toLowerCase().replace(':00','')===hour.toLowerCase());const classes=items.filter(x=>x.state==='ongoing').length,reserved=items.filter(x=>x.state==='reserved').length,available=items.filter(x=>x.state==='available').length;return <div className="timetable-cell" key={hour}><span>{hour}</span><div className="timetable-summary"><span className="ongoing">{classes} in class</span><span className="reserved">{reserved} reserved</span><span className="available">{available} open</span><details><summary>View facilities</summary>{items.map(x=><div className={`admin-slot ${x.state}`} key={x.id}><strong>{x.title}</strong><small>{x.space}</small><button title="Remove schedule item" onClick={()=>onRemoveSlot(x.id)}><X size={11}/></button></div>)}</details></div></div>})}</div>);
 return <div className="page-content inner-page"><div className="eyebrow"><span className="eyebrow-line"/> MANAGEMENT · OPERATIONS PORTAL</div><h1>Campus <span>operations.</span></h1><p className="hero-sub">Publish facility schedules and keep an eye on live booking traffic. Student bookings confirm instantly.</p><div className="admin-stats"><div><span>STUDENT ACCOUNTS</span><b>{traffic.students}</b><em>Registered in the 20X database</em></div><div><span>BOOKINGS</span><b>{traffic.bookings}</b><em>Confirmed directly by students</em></div><div><span>RESOURCES IN USE</span><b>{traffic.resourcesInUse}</b><em>With at least one booking</em></div><div><span>COMMUNITIES</span><b>27</b><em>General + department groups</em></div></div>
  <section className="inner-panel admin-week-panel"><div className="panel-heading"><div><div className="section-kicker">CAMPUS FACILITIES</div><h2>Hourly timetable<span className="title-period">.</span></h2></div><span className="schedule-sample-note">ALL WEEK · 9 AM – 6 PM</span></div><div className="availability-legend"><span><i className="legend-dot red"/> Class / in use</span><span><i className="legend-dot yellow"/> Reserved</span><span><i className="legend-dot green"/> Available / open</span></div><div className="weekly-hour-grid">{hoursGrid}</div><div className="schedule-editor"><div><label className="form-label">DAY</label><select className="form-input" value={day} onChange={e=>setDay(e.target.value)}>{weekDays.map((d,i)=><option value={i} key={d}>{d}</option>)}</select></div><div><label className="form-label">TIME</label><select className="form-input" value={time} onChange={e=>setTime(e.target.value)}>{hours.map(t=><option key={t}>{t}</option>)}</select></div><div><label className="form-label">RESOURCE</label><select className="form-input" value={resourceId} onChange={e=>setResourceId(e.target.value)}>{facilities.map(r=><option key={r[0]} value={r[0]}>{r[1]}</option>)}</select></div><div><label className="form-label">SCHEDULE ITEM</label><input className="form-input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Class, reserved hour, or open lab"/></div><div><label className="form-label">STATUS</label><select className="form-input" value={state} onChange={e=>setState(e.target.value)}><option value="ongoing">Class / in use</option><option value="reserved">Reserved</option><option value="available">Available to book</option></select></div><button className="primary-btn" disabled={!title.trim()} onClick={saveSlot}><Plus size={14}/> Publish</button></div></section>
  <section className="inner-panel traffic-panel"><div className="panel-heading"><div><div className="section-kicker">LIVE USAGE</div><h2>Most booked resources<span className="title-period">.</span></h2></div><span className="schedule-sample-note">UPDATES EVERY 10 SECONDS</span></div>{traffic.byResource?.length?traffic.byResource.map((item,i)=><div className="traffic-row" key={item.resource}><span className="traffic-rank">{String(i+1).padStart(2,'0')}</span><b>{item.resource}</b><div className="traffic-track"><i style={{width:`${Math.max(8,100*item.bookings/Math.max(...traffic.byResource.map(x=>x.bookings)))}%`}}/></div><strong>{item.bookings}</strong></div>):<div className="empty-state"><CalendarDays size={22}/><b>No bookings yet</b><span>New student bookings will show here automatically.</span></div>}</section>
 </div>
}

export function StudentDirectory(){
 const[students,setStudents]=useState([]),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/students').then(r=>r.ok?r.json():Promise.reject()).then(setStudents).catch(()=>setError('Could not load the student database.'))},[]);
 return <div className="page-content inner-page"><div className="eyebrow"><span className="eyebrow-line"/> MANAGEMENT · STUDENTS</div><h1>Student <span>database.</span></h1><p className="hero-sub">Registration numbers and departments created through student sign-up.</p><div className="inner-panel directory-panel"><div className="panel-heading"><div><div className="section-kicker">20X SQLITE DATABASE</div><h2>{students.length} student accounts<span className="title-period">.</span></h2></div><Users size={19}/></div>{error?<div className="auth-error">{error}</div>:students.length?students.map(s=><div className="student-record" key={s.registration}><div className="avatar">{s.registration.slice(0,2)}</div><b>{s.registration}</b><span>{s.department}</span><small>Joined {new Date(s.createdAt+'Z').toLocaleDateString()}</small></div>):<div className="empty-state"><Users size={22}/><b>No students registered yet</b><span>Student accounts will appear here after sign-up.</span></div>}</div></div>
}

export function MonthlyAnalytics(){
 const[month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)),[report,setReport]=useState(null),[error,setError]=useState(''),[usageQuery,setUsageQuery]=useState(''),[showAllResources,setShowAllResources]=useState(false);
 useEffect(()=>{let active=true;fetch(`/api/analytics/monthly?month=${month}`).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||'Unable to load this report.');return data}).then(data=>{if(active){setReport(data);setError('')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[month]);
 const maxBookings=Math.max(1,...(report?.byResource||[]).map(x=>x.bookings));
 const maxDaily=Math.max(1,...(report?.daily||[]).map(x=>x.bookings));
 const prettyMonth=new Date(`${month}-01T12:00:00`).toLocaleDateString(undefined,{month:'long',year:'numeric'});
 const least=report?.leastUsed;
 const matchingResources=(report?.byResource||[]).filter(resource=>resource.name.toLowerCase().includes(usageQuery.trim().toLowerCase()));
 const shownResources=showAllResources||usageQuery.trim()?matchingResources:matchingResources.slice(0,8);
 return <div className="page-content inner-page"><div className="eyebrow"><span className="eyebrow-line"/> MANAGEMENT · MONTHLY REPORT</div><div className="analytics-title-row"><div><h1>Monthly <span>analysis.</span></h1><p className="hero-sub">Campus bookings and facility use for {prettyMonth}.</p></div><label className="analytics-month">REPORT MONTH<input className="form-input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div>
  {error&&<div className="auth-error">{error}</div>}{!report&&!error&&<div className="inner-panel">Loading the monthly report…</div>}{report&&<>
   <div className="admin-stats analytics-stats"><div><span>BOOKING TRAFFIC</span><b>{report.bookings}</b><em>Confirmed bookings this month</em></div><div><span>ACTIVE STUDENTS</span><b>{report.students}</b><em>Unique student accounts booking</em></div><div><span>RESOURCES USED</span><b>{report.resourcesBooked}<small> / {report.totalResources}</small></b><em>Facilities with a booking</em></div><div><span>UNUSED RESOURCES</span><b>{report.unusedResources}</b><em>No booking recorded this month</em></div></div>
   <div className="analytics-highlights"><div><span className="analytics-icon"><BarChart3 size={17}/></span><small>MOST USED</small><b>{report.topResource?.name||'No bookings yet'}</b><em>{report.topResource?`${report.topResource.bookings} bookings`: 'No activity recorded'}</em></div><div><span className="analytics-icon violet"><Activity size={17}/></span><small>LEAST USED</small><b>{least?.name||'No resources listed'}</b><em>{least?`${least.bookings} bookings this month`:'No activity recorded'}</em></div><div><span className="analytics-icon"><CalendarDays size={17}/></span><small>BUSIEST DAY</small><b>{report.busiestDay?new Date(`${month}-${String(report.busiestDay.day).padStart(2,'0')}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'No activity yet'}</b><em>{report.busiestDay?`${report.busiestDay.bookings} bookings`: 'No bookings recorded'}</em></div><div><span className="analytics-icon violet"><Clock3 size={17}/></span><small>PEAK HOUR</small><b>{report.peakTime?.[0]||'No activity yet'}</b><em>{report.peakTime?`${report.peakTime[1]} bookings began then`:'No bookings recorded'}</em></div></div>
   <section className="inner-panel analytics-panel"><div className="panel-heading"><div><div className="section-kicker">DAILY TRAFFIC</div><h2>Bookings by day<span className="title-period">.</span></h2></div><span className="schedule-sample-note">{report.bookings} TOTAL</span></div><div className="daily-chart" role="img" aria-label={`Daily bookings for ${prettyMonth}`}>{report.daily.map(d=><div className="daily-bar-wrap" key={d.day} title={`${prettyMonth.split(' ')[0]} ${d.day}: ${d.bookings} bookings`}><span className="daily-bar-value">{d.bookings||''}</span><div className="daily-bar" style={{height:`${Math.max(d.bookings?8:2,100*d.bookings/maxDaily)}%`}}/><small>{d.bookings?d.day:''}</small></div>)}</div></section>
   <section className="inner-panel analytics-panel analytics-usage-panel"><div className="panel-heading"><div><div className="section-kicker">FACILITY USAGE</div><h2>Bookings by resource<span className="title-period">.</span></h2><p className="analytics-panel-note">Ranked by confirmed bookings for {prettyMonth}.</p></div><span className="analytics-count">{report.totalResources} facilities</span></div><div className="analytics-usage-controls"><label><span className="sr-only">Filter facilities</span><input className="form-input" value={usageQuery} onChange={e=>setUsageQuery(e.target.value)} placeholder="Search facilities by name"/></label>{!usageQuery.trim()&&<button className="analytics-expand" onClick={()=>setShowAllResources(value=>!value)}>{showAllResources?'Show top 8':`Show all ${report.totalResources}`}</button>}</div><div className="analytics-resource-list">{shownResources.map((resource,i)=><div className="analytics-resource" key={resource.id}><span className="analytics-rank">{String(i+1).padStart(2,'0')}</span><b title={resource.name}>{resource.name}</b><div className="analytics-track"><i style={{width:`${Math.max(resource.bookings?5:0,100*resource.bookings/maxBookings)}%`}}/></div><strong>{resource.bookings}<small> bookings</small></strong></div>)}</div>{shownResources.length===0&&<div className="analytics-no-results">No facilities match “{usageQuery}”.</div>}</section>
  </>}
 </div>
}
